#promtail-config.yaml
server:
  http_listen_port: 9080

positions:
  # Speichert die Position, bis zu der Logs gelesen wurden, um Dubletten zu vermeiden
  filename: /tmp/positions.yaml

clients:
  # Ziel-URL des Loki-Servers (via Docker Service Discovery)
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          # Liest alle Log-Dateien aus /var/log des Hosts
          __path__: /var/log/*.log 
